Home user interface done
Rebels-Y3S2/STOP-SMOKING-MOBILE pull request #31
Opened 2022-10-30 10:14 UTC by ShivaaniDushya

2022-10-30 14:33 UTC, amanthajayathilake requested changes
In App.js
**Remove this and**
import { MainStackNavigator } from './src/navigation/stackNavigator.js';

**Add**
import { MainStackNavigator } from './src/navigation/StackNavigator.js';

2022-10-31 10:29 UTC, Shehanx86 approved these changes

2022-11-01 11:04 UTC, dulshan-perera approved these changes
LGTM

2022-11-01 19:47 UTC, dulshan-perera commented on src/pages/UserProfile/UpdateProfile.js
> +                    />
There is a reusable dropdown component in the Components section.

2022-11-01 19:49 UTC, dulshan-perera requested changes
Check the reusable dropdown component

2022-11-03 16:37 UTC, amanthajayathilake approved these changes

2022-11-03 16:58 UTC, dulshan-perera approved these changes
Changes done. Minor issues exist. Let's fix them in the next update.

2022-11-03 16:58 UTC, merged